apiVersion: v1
kind: Service
metadata:
  name: {{ include "ortelius-chart.fullname" . }}
  labels:
    {{- include "ortelius-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  type: NodePort
  selector:
    {{- include "ortelius-chart.selectorLabels" . | nindent 4 }}
