apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ortelius-rule
spec:
  host: dmadminweb
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
  - name: v3
    labels:
      version: v3

